-- MySQL Script generated by MySQL Workbench
-- jeu. 23 juil. 2020 10:16:11 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema modelcars
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `modelcars` ;

-- -----------------------------------------------------
-- Schema modelcars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelcars` DEFAULT CHARACTER SET utf8mb4 ;
USE `modelcars` ;

-- -----------------------------------------------------
-- Table `modelcars`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelcars`.`car` ;

CREATE TABLE IF NOT EXISTS `modelcars`.`car` (
  `id` INT(11) NOT NULL,
  `mark` VARCHAR(45) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `year` INT(11) NULL DEFAULT NULL,
  `period_of_production` VARCHAR(10) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `model` VARCHAR(100) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `version` VARCHAR(45) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `energy` ENUM('Electrique', 'Hybride', 'Thermique') CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `url_photo` VARCHAR(255) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `category` VARCHAR(45) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `color` VARCHAR(45) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `color_name` VARCHAR(100) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `maker` VARCHAR(45) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `material_number` VARCHAR(45) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `date_of_purchase` DATE NULL DEFAULT NULL,
  `price` DECIMAL(4,2) NULL DEFAULT NULL,
  `currency` VARCHAR(4) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `dealer` VARCHAR(100) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `scale` VARCHAR(45) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `comment` VARCHAR(255) COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelcars`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelcars`.`migrations` ;

CREATE TABLE IF NOT EXISTS `modelcars`.`migrations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `run_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
